config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  post "users/login", to: "users#login"
  resources :users
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :admins
  resources :order_items
  resources :orders
  post "/all_orders", to: "all_orders#show"
  get "/all_orders", to: "all_orders#index"
  resources :all_orders
  resources :menu_items
  resources :menu_categories
  get "/items", to: "items#show"
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :order_items
  has_secure_password

  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :first_name, length: { minimum: 3 }
  validates :email, length: { minimum: 5 }
  validates :password, length: { minimum: 8 }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    render "index"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      ph_no: params[:ph_no],
      password: params[:password],
      role: "admin",
    )

    if new_user.save
      user = User.find_by(email: params[:email])
      session[:current_user_id] = user.id
      redirect_to admins_path
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/admins/new"
    end
  end
end

app/controllers/all_orders_controller.rb
class AllOrdersController < ApplicationController
  def index
    render "index"
  end

  def update
    id = params[:id].to_i
    orders = Order.where("user_id = ?", id)
    for i in orders
      if i.delivered == false
        i.delivered = true
        i.save!
        break
      end
    end
    redirect_to admins_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to menu_items_path
    else
      render "index"
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    render "index"
  end

  def create
    items = MenuItem.all
    count = MenuItem.all.count
    maxCount = 0
    count = count - 1
    for i in 0..count
      if items.pluck(:menu_category_id)[i] > maxCount
        maxCount = items.pluck(:menu_category_id)[i]
      end
    end
    maxCount = maxCount + 1
    new_item = MenuItem.new(
      menu_category_id: maxCount,
      name: params[:name],
      description: params[:desc],
      price: params[:price].to_i,
    )

    if new_item.save
      redirect_to admins_path
    end
  end

  def destroy
    id = params[:id].to_i
    menu = MenuItem.find(MenuItem.where("menu_category_id = ?", id).pluck(:id)[0])
    menu.destroy
    redirect_to admins_path
  end

  def show
    render "edit"
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[ show edit update destroy ]

  def index
    render "index"
  end
end

app/controllers/orders_controller.rb
require "date"

class OrdersController < ApplicationController
  def destroy
    id = params[:id].to_i

    do_order = Order.new(
      date: Date.today,
      user_id: id,
      delivered: false,
    )

    do_order.save

    order = OrderItem.find(OrderItem.where("order_id = ?", id).pluck(:id))
    for i in order
      i.destroy
    end
    redirect_to orders_path
  end

  def update
    redirect_to menu_items_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      if user.role == "customer"
        redirect_to menu_items_path
      else
        redirect_to admins_path
      end
    else
      flash[:error] = "Invalid E-Mail ID or Password"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render plain: User.order(:id).map { |user| user.to_displayable_string }.join("\n")
  end

  def show
    id = params[:id]
    user = User.find(id)
    render plain: user.to_displayable_string
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      ph_no: params[:ph_no],
      password: params[:password],
      role: "customer",
    )

    if new_user.save
      user = User.find_by(email: params[:email])
      session[:current_user_id] = user.id
      redirect_to menu_items_path
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end
  end

  def login
    def login
      email = params[:email]
      password = params[:password]
      users = User.where("email = ? and password_digest = ?", email, password)
      response = !users.empty?
      render plain: response
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_categories_helper.rb
module MenuCategoriesHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="Login-Header">
      <img src="Cocafe-logo.jpeg" alt="Logo" />
    </div><div class="Centered">
    <span class="Welcome">
      <br><br>
      CoCafe
    </span>
  </div>
    <br>
    <article class="Login-Article">
      <div>Check Pending Delivery ?</div>
      <div class="SignUp">
      <%= link_to "See Pending Deliveries", all_orders_path, method: "post", id: "IN" %>
    </div>
      <br />
    </article>
    <article class="Login-Article">
      <div>Add Admin ?</div>
      <div class="SignUp">
      <%= link_to "Add Admin Here", new_admin_path, id: "UP" %>
    </div>
      <br />
    </article>
    <article class="Login-Article">
      <div>Add Item ?</div>
      <div class="SignUp">
      <%= link_to "Add Item Here", new_item_path, id: "IN" %>
    </div>
      <br />
    </article>
    <article class="Login-Article">
      <div>All Food Items ?</div>
      <div class="SignUp">
      <%= link_to "See Food Items Here", items_path, method: "get", id: "IN" %>
    </div>
      <br />
    </article>
    <br>
    <div class="Center-It"><%= link_to "Sign Out", destroy_session_path, method: "delete", :id => 'Admin-Sign-Out' %></div>
  </body>
</html>

app/views/admins/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>New Admin</title>
  </head>
  <body class="Signup-Body">
    <article class="Signup-Article">
      <div class="Login-Header">
        <img src="Cocafe-logo.jpeg" alt="Cocafe-Logo" />
      </div>
      <br />
      <tag class="Cocafe-Tag"> CoCafe </tag>
    </article>
    <article class="Signup-Article-Form">
      <%= form_with url: admins_path do |form| %>
      <div>Add An Admin Account</div>
      <br /><br>
      <span class="Email-Text"> First Name </span>
      <br />
      <%= form.text_field :first_name, class: "Login-Input-Email", :autofocus => true %>
      <br /><br>
      <span class="Email-Text"> Last Name </span>
      <br />
      <%= form.text_field :last_name, class: "Login-Input-Email" %>
      <br /><br>
      <span class="Email-Text"> E-Mail Address </span>
      <br />
      <%= form.email_field :email, class: "Login-Input-Email" %>
      <br /><br>
      <span class="Email-Text"> Phone Number </span>
      <br />
      <%= form.text_field :ph_no, class: "Login-Input-Email" %>
      <br /><br>
      <span class="Email-Text"> Password </span>
      <br />
      <%= form.password_field :password, class: "Login-Input-Password" %>
      <br /><br>
      <br />
      <%= form.submit "Sign-up", class: "Form-submit" %>
      <% end %>
      <br /><br />
    </article>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoCafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>