config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  post "users/login", to: "users#login"
  resources :users
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :admins
  resources :order_items
  resources :orders
  post "/all_orders", to: "all_orders#show"
  get "/all_orders", to: "all_orders#index"
  resources :all_orders
  resources :menu_items
  resources :menu_categories
  get "/items", to: "items#show"
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :order_items
  has_secure_password

  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :first_name, length: { minimum: 3 }
  validates :email, length: { minimum: 5 }
  validates :password, length: { minimum: 8 }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    render "index"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      ph_no: params[:ph_no],
      password: params[:password],
      role: "admin",
    )

    if new_user.save
      user = User.find_by(email: params[:email])
      session[:current_user_id] = user.id
      redirect_to admins_path
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/admins/new"
    end
  end
end

app/controllers/all_orders_controller.rb
class AllOrdersController < ApplicationController
  def index
    render "index"
  end

  def update
    id = params[:id].to_i
    orders = Order.where("user_id = ?", id)
    for i in orders
      if i.delivered == false
        i.delivered = true
        i.save!
        break
      end
    end
    redirect_to admins_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to menu_items_path
    else
      render "index"
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    render "index"
  end

  def create
    items = MenuItem.all
    count = MenuItem.all.count
    maxCount = 0
    count = count - 1
    for i in 0..count
      if items.pluck(:menu_category_id)[i] > maxCount
        maxCount = items.pluck(:menu_category_id)[i]
      end
    end
    maxCount = maxCount + 1
    new_item = MenuItem.new(
      menu_category_id: maxCount,
      name: params[:name],
      description: params[:desc],
      price: params[:price].to_i,
    )

    if new_item.save
      redirect_to admins_path
    end
  end

  def destroy
    id = params[:id].to_i
    menu = MenuItem.find(MenuItem.where("menu_category_id = ?", id).pluck(:id)[0])
    menu.destroy
    redirect_to admins_path
  end

  def show
    render "edit"
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[ show edit update destroy ]

  def index
    render "index"
  end
end

app/controllers/orders_controller.rb
require "date"

class OrdersController < ApplicationController
  def destroy
    id = params[:id].to_i

    do_order = Order.new(
      date: Date.today,
      user_id: id,
      delivered: false,
    )

    do_order.save

    order = OrderItem.find(OrderItem.where("order_id = ?", id).pluck(:id))
    for i in order
      i.destroy
    end
    redirect_to orders_path
  end

  def update
    redirect_to menu_items_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      if user.role == "customer"
        redirect_to menu_items_path
      else
        redirect_to admins_path
      end
    else
      flash[:error] = "Invalid E-Mail ID or Password"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render plain: User.order(:id).map { |user| user.to_displayable_string }.join("\n")
  end

  def show
    id = params[:id]
    user = User.find(id)
    render plain: user.to_displayable_string
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      ph_no: params[:ph_no],
      password: params[:password],
      role: "customer",
    )

    if new_user.save
      user = User.find_by(email: params[:email])
      session[:current_user_id] = user.id
      redirect_to menu_items_path
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end
  end

  def login
    def login
      email = params[:email]
      password = params[:password]
      users = User.where("email = ? and password_digest = ?", email, password)
      response = !users.empty?
      render plain: response
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_categories_helper.rb
module MenuCategoriesHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/all_orders/_AllOrder-section.html.erb
<% Order.order(:date).each do |order| %>
<% if order.user_id == @current_user.id %>
<div class="Order-Page">
  <div class="Row">Date of Order: <%= order.date %></div>
  <div class="Row">Order ID: <%= order.id %></div>
  <div class="Row">Status: <%= order.delivered ? "Delivered" : "On The Way" %></div>
</div>
<% end %>
<% end %>

app/views/all_orders/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CoCafe</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- <link href="CssDesign.css" rel="stylesheet" /> -->
  </head>
  <body id="FrontPage-Body">
    <header>
      <img src="Cocafe-logo.jpeg" alt="Cafeteria Logo" />
      <div>CoCafe</div>
      <div class="FrontPage-Search">
        <input type="text" placeholder="What are you looking for?" />
        <button type="submit"></button>
      </div>
      <span id="Name">
      Hi! <%= @current_user.first_name %>
      </span>
      <%= link_to "Sign Out", destroy_session_path, method: "delete", :id => 'Sign-Out' %>
    </header>

    <navbar>
      <ul class="Navigation">
          <li><%= link_to "Menu", menu_items_path %></li>
          <li><%= link_to "All Orders", all_orders_path %></li>
      </ul>
    </navbar>

    <br /><br />

    <article class="Dishes">
      <%= render partial: "AllOrder-section" %>
    </article>
    <footer> </footer>
  </body>
</html>

app/views/all_orders/show.html.erb
<% Order.order(:date).each do |order| %>
<%  if !order.delivered %>
<div class="Order-Admin">
  <%= form_with(url: "/all_orders/#{order.user_id}", method: "put") do %>
  <div class="Row-New">Current Order To Be Delivered</div>
  <div class="Row-New">Date of Order: <%= order.date %></div>
  <div class="Row-New">Order ID: <%= order.id %></div>
  <%= button_tag("Mark As Delivered", type: "submit", class: "Add-To-Orders", :value => order.user_id, :name => "id") %>
  <% end %>
</div>
<% break %>
<% end %>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="Login-Header">
      <img src="Cocafe-logo.jpeg" alt="Logo" />
    </div><div class="Centered">
    <span class="Welcome">
      <br><br>
      Welcome to CoCafe !!
    </span>
  </div>
    <br>
    <article class="Login-Article">
      <div>New User ?</div>
      <div class="SignUp">
      <%= link_to "Sign Up here", new_user_path, id: "UP" %>
    </div>
      <br /><br /><br>
    </article>
    <article class="Login-Article">
      <div>Existing User ?</div>
      <div class="SignUp">
      <%= link_to "Sign In here", new_sessions_path, id: "IN" %>
    </div>
      <br /><br /><br>
    </article>
    <br />
  </body>
</html>

app/views/items/_Item-section.html.erb
<% MenuItem.order(:menu_category_id).each do |menu| %>
<div class="Dish-Card">
  <%= form_with(url: "/items/#{menu.menu_category_id}", method: "delete") do %>
  <img class="Dish" src=<%= menu.description %>/>
  <div class="Dish-Name"><%= menu.name %></div>
  <div class="Dish-Price">Price: ₹ <%= menu.price %></div>
  <%= button_tag("Remove From Menu", type: "submit", class: "Remove-From-Orders", :value => menu.menu_category_id, :name => "id") %>
  <% end %>
</div>
<% end %>

app/views/items/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CoCafe</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- <link href="CssDesign.css" rel="stylesheet" /> -->
  </head>
  <body id="FrontPage-Body">
    <br /><br />
    <span class="Menu-Text">MENU</span>
    <br /><br />

    <article class="Dishes">
      <%= render partial: "Item-section" %>
    </article>
    <footer> </footer>
  </body>
</html>

app/views/items/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Item</title>
  </head>
  <body>
    <div class="Login-Header">
      <img src="Cocafe-logo.jpeg" alt="Logo" />
    </div>
    <br>
    <div id="Error">
      <%= flash[:error] %>
    </div>
    <article class="Login-Article">
      <div>Add New Food Item</div>
      <%= form_with url: items_path do |form| %>
      <br /><br><br>
      <span class="Email-Text"> Name of Item </span>
      <br />
      <%= form.text_field :name, :autofocus => true %>
      <br /><br>
      <span class="Email-Text"> Image URL / File Name </span>
      <br />
      <%= form.text_field :desc %>
      <br /><br>
      <span class="Email-Text"> Price of Item </span>
      <br />
      <%= form.text_field :price %>
      <br /><br /><br>
      <%= form.submit "Add Item", class: "Form-submit" %>
      <br /><br /><br>
  <% end %>
      <br /><br />
    </article>
    <br />
  </body>
</html>