config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  post "users/login", to: "users#login"
  resources :users
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :admins
  resources :order_items
  resources :orders
  post "/all_orders", to: "all_orders#show"
  get "/all_orders", to: "all_orders#index"
  resources :all_orders
  resources :menu_items
  resources :menu_categories
  get "/items", to: "items#show"
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    iid = params[:id].to_i
    uid = current_user.id
    name = MenuItem.find(iid).name
    desc = MenuItem.find(iid).description
    price = MenuItem.find(iid).price
    new_order = OrderItem.new(
      order_id: uid,
      menu_item_id: iid,
      menu_item_name: name,
      menu_item_price: price,
    )
    new_order.save
    redirect_to order_items_path
  end

  def destroy
    id = params[:id].to_i
    order = OrderItem.find(OrderItem.where("order_id = ? and menu_item_id = ?", current_user.id, id).pluck(:id)[0])
    order.destroy
    redirect_to order_items_path
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_CartItem-section.html.erb
<% OrderItem.order(:menu_item_id).each do |menu| %>
<div class="Dish-Card">
  <%= form_with(url: "/order_items/#{menu.menu_item_id}", method: "delete") do %>
  <img class="Dish" src=<%= MenuItem.find(menu.menu_item_id).description %>>/>
  <div class="Dish-Name"><%= menu.menu_item_name %></div>
  <div class="Dish-Price">Price: ₹ <%= menu.menu_item_price %></div>
  <span class="Quantity" style="display: flex">
  <div class="centerit">
    <img src="minus.png"/>
    <span>1</span>
    <img src="plus.png"/>
  </div>
  </span>
  <%= button_tag("Remove From Orders", type: "submit", class: "Remove-From-Orders", :value => menu.menu_item_id, :name => "id") %>
  <% end %>
</div>
<% end %>

app/views/order_items/_MenuItem-section.html.erb
<% MenuItem.order(:menu_category_id).each do |menu| %>
<div class="Dish-Card">
  <%= form_with(url: "/order_items", method: "post") do %>
  <img class="Dish" src=<%= menu.description %>/>
  <div class="Dish-Name"><%= menu.name %></div>
  <div class="Dish-Price">Price: ₹ <%= menu.price %></div>
  <%= button_tag("Add To Orders", type: "submit", class: "Add-To-Orders", :value => menu.menu_category_id, :name => "id") %>
  <% end %>
</div>
<% end %>

app/views/order_items/_form.html.erb
<%= form_with(model: order_item) do |form| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
        <% order_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :menu_item_id %>
    <%= form.text_field :menu_item_id %>
  </div>

  <div class="field">
    <%= form.label :menu_item_name %>
    <%= form.text_field :menu_item_name %>
  </div>

  <div class="field">
    <%= form.label :menu_item_price %>
    <%= form.text_field :menu_item_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CoCafe</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- <link href="CssDesign.css" rel="stylesheet" /> -->
  </head>
  <body id="FrontPage-Body">
    <header>
      <img src="Cocafe-logo.jpeg" alt="Cafeteria Logo" />
      <div>CoCafe</div>
      <div class="FrontPage-Search">
        <input type="text" placeholder="What are you looking for?" />
        <button type="submit"></button>
      </div>
      <span id="Name">
      Hi! <%= @current_user.first_name %>
      </span>
      <%= link_to "Sign Out", destroy_session_path, method: "delete", :id => 'Sign-Out' %>
    </header>

    <navbar>
      <ul class="Navigation">
          <li><%= link_to "Menu", menu_items_path %></li>
          <li><%= link_to "All Orders", all_orders_path %></li>
      </ul>
    </navbar>

    <br /><br />
    <span class="Menu-Text">MENU</span>
    <br /><br />
    <article class="Dishes">
      <%= render partial: "MenuItem-section" %>
    </article>
    <article class="Popup-Cart">
      <%= render partial: "CartItem-section" %>
      <% sum = 0 %>
      <% OrderItem.order(:menu_item_id).each do |order| %>
      <% sum  = sum + order.menu_item_price %>
      <% end %>
      <div class="Total-Price">Total Price: ₹ <%= sum %></div>
      <br>
      <%= form_with(url: "/menu_categories", method: "get") do %>
      <div class="Checkout-button">
        <%= button_tag("Proceed To Checkout", class: "", type: "submit", :value => sum, :name => "payment") %>
      </div>
      <% end %>
    </article>
  </body>
</html>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<p>
  <strong>Menu item:</strong>
  <%= @order_item.menu_item_id %>
</p>

<p>
  <strong>Menu item name:</strong>
  <%= @order_item.menu_item_name %>
</p>

<p>
  <strong>Menu item price:</strong>
  <%= @order_item.menu_item_price %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>